export const initialDiyetisyenData = {
  diyetisyen: {
    fullName: "Dyt. Mustafa Yalçın",
    uzmanlik: "Klinik Beslenme",
  },

  danisanlar: [
    {
      id: 1,
      fullName: "Gözde Yalçın",
      yas: 24,
      boy: 165,
      kilo: 68,
      hedef: 60,
      alerji: "Laktoz hassasiyeti",
      hastalik: "Yok",
      sonGorusme: "22.04.2026",
      durum: "Aktif",
    },
    {
      id: 2,
      fullName: "Arman Yalçın",
      yas: 29,
      boy: 170,
      kilo: 74,
      hedef: 65,
      alerji: "Yok",
      hastalik: "İnsülin direnci",
      sonGorusme: "21.04.2026",
      durum: "Aktif",
    },
    {
      id: 3,
      fullName: "Neylan Yalçın",
      yas: 32,
      boy: 160,
      kilo: 81,
      hedef: 72,
      alerji: "Gluten hassasiyeti",
      hastalik: "Tiroid takibi",
      sonGorusme: "18.04.2026",
      durum: "Pasif",
    },
  ],

  planlar: [
    {
      id: 1,
      danisanId: 1,
      danisanAdi: "Gözde Yalçın",
      baslik: "Kilo Kontrol Planı",
      planTuru: "Kilo Verme",
      danisanKilo: 68,
      baslangicTarihi: "2026-04-20",
      bitisTarihi: "2026-05-20",
      hedefKalori: 1600,
      suHedefi: 2380,
      durum: "Aktif",
      not: "Öğünlerde protein dengesine dikkat edilecek.",
      toplamKalori: 1550,
      olusturmaTarihi: "20.04.2026",
      ogunler: [
        {
          id: 1,
          ogunAdi: "Kahvaltı",
          saat: "08:30",
          icerik: "Yulaf, süt, muz",
          kalori: 350,
        },
        {
          id: 2,
          ogunAdi: "Öğle",
          saat: "13:00",
          icerik: "Tavuk salata, yoğurt",
          kalori: 500,
        },
        {
          id: 3,
          ogunAdi: "Akşam",
          saat: "19:00",
          icerik: "Sebze yemeği, bulgur, ayran",
          kalori: 450,
        },
        {
          id: 4,
          ogunAdi: "Ara Öğün",
          saat: "16:30",
          icerik: "1 porsiyon meyve, 10 badem",
          kalori: 250,
        },
      ],
    },
    {
      id: 2,
      danisanId: 2,
      danisanAdi: "Arman Yalçın",
      baslik: "Yağ Yakım Planı",
      planTuru: "Kilo Verme",
      danisanKilo: 74,
      baslangicTarihi: "2026-04-18",
      bitisTarihi: "2026-05-18",
      hedefKalori: 1700,
      suHedefi: 2590,
      durum: "Aktif",
      not: "Basit karbonhidrat azaltılacak.",
      toplamKalori: 1680,
      olusturmaTarihi: "18.04.2026",
      ogunler: [
        {
          id: 1,
          ogunAdi: "Kahvaltı",
          saat: "09:00",
          icerik: "2 yumurta, peynir, tam buğday ekmeği",
          kalori: 420,
        },
        {
          id: 2,
          ogunAdi: "Öğle",
          saat: "13:30",
          icerik: "Izgara tavuk, bol yeşillikli salata",
          kalori: 480,
        },
        {
          id: 3,
          ogunAdi: "Akşam",
          saat: "19:30",
          icerik: "Çorba, yoğurt, sebze yemeği",
          kalori: 430,
        },
        {
          id: 4,
          ogunAdi: "Ara Öğün",
          saat: "16:00",
          icerik: "Kefir ve ceviz",
          kalori: 350,
        },
      ],
    },
  ],

  gunlukKayitlar: [
    {
      id: 1,
      danisanAdi: "Gözde Yalçın",
      ogun: "Kahvaltı",
      detay: "Yulaf, süt, muz",
      kalori: 320,
      su: 2,
      tarih: "22.04.2026",
    },
    {
      id: 2,
      danisanAdi: "Arman Yalçın",
      ogun: "Öğle",
      detay: "Tavuk salata",
      kalori: 410,
      su: 3,
      tarih: "22.04.2026",
    },
    {
      id: 3,
      danisanAdi: "Neylan Yalçın",
      ogun: "Akşam",
      detay: "Çorba, yoğurt",
      kalori: 260,
      su: 1,
      tarih: "22.04.2026",
    },
  ],

  onayBekleyenler: [
    {
      id: 1,
      danisanAdi: "Gözd",
      talep: "Beslenme planı güncelleme isteği",
      tarih: "20.04.2026",
    },
    {
      id: 2,
      danisanAdi: "Merve Aydın",
      talep: "Yeni günlük kayıt onayı",
      tarih: "20.04.2026",
    },
  ],

  bildirimler: [
    {
      id: 1,
      mesaj: "Gözde Yalçın yeni bir günlük kayıt ekledi.",
      saat: "09:15",
    },
    {
      id: 2,
      mesaj: "Arman Yalçın su hedefini tamamladı.",
      saat: "11:40",
    },
    {
      id: 3,
      mesaj: "Neylan Yalçın plan güncelleme talebi gönderdi.",
      saat: "13:05",
    },
  ],
};